{{- if .Values.masterKey }}
apiVersion: v1
kind: Secret
metadata:
  name: local-llm-hub-secrets
  labels:
    {{- include "llh.labels" . | nindent 4 }}
type: Opaque
stringData:
  LITELLM_MASTER_KEY: {{ .Values.masterKey | quote }}
{{- end }}
